server:
  port: 30000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.194:3306/youbanban_order?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: akazam
    password: dbacc355
  mvc:
    view:
      prefix: /views/
      suffix: .html


logging:
  level:
    com.esurfing.tianmao.dao: debug